42 restaurant overview
GSG-G10/food-hub pull request #51
Opened 2021-10-31 18:12 UTC by Ahmad-Omar

2021-10-31 18:16 UTC, NourAdawi approved these changes

2021-11-04 11:04 UTC, NourAdawi requested changes
when requesting (restaurant/:id) and the id is not in database, the app crashes because the values are undefined 
![image](https://user-images.githubusercontent.com/23521963/140302963-1b43ab58-d309-4c17-bc79-78b1a3441f69.png)

id of 3 doesn't exist in db
![image](https://user-images.githubusercontent.com/23521963/140303032-2ed78882-b2d9-441c-b2ff-887e0f016927.png)

2021-11-04 11:11 UTC, NourAdawi reviewed
![image](https://user-images.githubusercontent.com/23521963/140303880-29e43c80-03ac-4d6e-9cd1-6f3e92574acf.png)

the opening icons are amazing! 😍

2021-11-04 12:21 UTC, Amoodaa commented on client/src/components/MealCard/index.js
> +    localStorage.setItem('cart', cart);
HMMMMMMMMMMMM i think we can make this better

2021-11-08 16:54 UTC, NourAdawi approved these changes

2021-11-08 17:03 UTC, M7Mansour approved these changes

2021-11-08 17:04 UTC, merged